version: "3"
services:
  portfolio:
    container_name: portfolio
    pull_policy: build
    build: .
    ports:
      - 3030:3000
    labels:
      - "traefik.http.routers.portfolio.rule=Host(`cheekysim.com`)"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik_default
